UniversityMVC/Models/Group.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace UniversityMVC.Models
{
    public class Group
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Id { set; get; }
        [Required(ErrorMessage = "Name is required")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "Incorrect Name")]
        public string Name { set; get; }
        public Course Course { set; get; }
    }
}

UniversityMVC/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using UniversityMVC.Models;

namespace UniversityMVC.Controllers
{
    public class GroupController : Controller
    {
        private readonly ILogger<GroupController> _logger;
        private IUnitOfWork UnitOfWork { get; set; }

        public GroupController(ILogger<GroupController> logger, IUnitOfWork unitOfWork)
        {
            _logger = logger;
            UnitOfWork = unitOfWork;
        }
        public IActionResult SelectedGroup(int? id)
        {
            if (id == null)
            {
                _logger.LogWarning("SelectedGroup method was called but got no id");
                return NotFound();
            }
            _logger.LogInformation("SelectedGroup method was called with an id = {groupId}", id);
            ViewBag.GroupName = $"{UnitOfWork.Groups.GetById(id).Name}";
            return View(UnitOfWork.Students.GetByGroup(id));
        }

        [HttpGet]
        public IActionResult ChangeGroup(int id)
        {
            _logger.LogInformation("ChangeGroup method was called with an id = {groupId}", id);
            return View(UnitOfWork.Groups.GetById(id));
        }

        [HttpPost]
        public IActionResult ChangeGroup(string name, int id)
        {
            UnitOfWork.Groups.GetById(id).Name = name;
            UnitOfWork.Save();
            _logger.LogInformation("Group's (id = {groupId}) name was changed to {newName}", id, name);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult DeleteGroup(int? id)
        {
            if (id == null)
            {
                _logger.LogWarning("DeleteGroup method was called but got no id");
                return NotFound();
            }
            try
            {

                _logger.LogInformation("DeleteGroup method was called with an id = {groupId}", id);
                return View(UnitOfWork.Groups.GetById(id));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An exception occurred");
                return NotFound();
            }
        }

        [HttpPost, ActionName("DeleteGroup")]
        public IActionResult ConfirmDeleteGroup(int id)
        {
            try
            {
                _logger.LogInformation("Attempt to delete a group with an id = {groupId}", id);
                UnitOfWork.Groups.Remove(UnitOfWork.Groups.GetById(id));
                UnitOfWork.Save();
            }
            catch (Microsoft.EntityFrameworkCore.DbUpdateException ex)
            {
                _logger.LogError(ex, "Attempt failed");
                ViewBag.Message = "Невозможно удалить группу, в которой есть студенты!";
                return View("ReturnHomePage");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Attempt failed");
                ViewBag.Message = "Во время выполнения запроса произошла ошибка! Изменения не были внесены! ";
                return View("ReturnHomePage");
            }

            _logger.LogInformation("Group was successfully deleted");
            ViewBag.Message = "Группа была удалена!";
            return View("ReturnHomePage");
        }
    }
}

UniversityMVC/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using UniversityMVC.Models;

namespace UniversityMVC.Controllers
{
    public class StudentController : Controller
    {
        private readonly ILogger<StudentController> _logger;
        private IUnitOfWork UnitOfWork { get; set; }

        public StudentController(ILogger<StudentController> logger, IUnitOfWork unitOfWork)
        {
            _logger = logger;
            UnitOfWork = unitOfWork;
        }

        [HttpGet]
        public IActionResult ChangeStudent(int id)
        {
            _logger.LogInformation("ChangeStudent method was called with an id = {studentId}", id);
            return View(UnitOfWork.Students.GetById(id));
        }

        [HttpPost]
        public IActionResult ChangeStudent(string firstName, string lastName, int id)
        {
            UnitOfWork.Students.GetById(id).FirstName = firstName;
            UnitOfWork.Students.GetById(id).LastName = lastName;
            UnitOfWork.Save();
            _logger.LogInformation("Student's (id = {groupId}) first name was changed to {newFirstName}, last name was changed to {newLastName}", id, firstName, lastName);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult DeleteStudent(int? id)
        {
            if (id == null)
            {
                _logger.LogWarning("DeleteStudent method was called but got no id");
                return NotFound();
            }
            try
            {
                _logger.LogInformation("DeleteStudent method was called with an id = {studentId}", id);
                return View(UnitOfWork.Students.GetById(id));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An exception occurred");
                return NotFound();
            }
        }

        [HttpPost, ActionName("DeleteStudent")]
        public IActionResult ConfirmDeleteStudent(int id)
        {
            try
            {
                _logger.LogInformation("Attempt to delete a student with an id = {studentId}", id);
                UnitOfWork.Students.Remove(UnitOfWork.Students.GetById(id));
                UnitOfWork.Save();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Attempt failed");
                ViewBag.Message = "Во время выполнения запроса произошла ошибка! Изменения не были внесены! ";
                return View("ReturnHomePage");
            }
            _logger.LogInformation("Student was successfully deleted");
            ViewBag.Message = "Студент был удалён";
            return View("ReturnHomePage");
        }
    }
}

UniversityMVC/Views/Group/ChangeGroup.cshtml
@model Group
@{
    ViewData["Title"] = "Group Change";
}
<h2>Введите новое название для группы @Model.Name:</h2>
<form asp-action="ChangeGroup" asp-controller="Group" asp-antiforgery="true">
    <div>
        <input type="hidden" value="@Model.Id" name="id" />
        <div>
            <label asp-for="Name">Название</label>
            <input type="text" asp-for="Name" />
            <span asp-validation-for="Name"></span>
        </div>
        <div>
            <input type="submit" value="Сохранить" />
        </div>
    </div>
</form>

UniversityMVC/Views/Group/DeleteGroup.cshtml
@model Group
@{
    ViewBag.Title = "Delete Group";
}

<div>
    <h3>Подтверждение удаления группы</h3>
    <dl class="dl-horizontal">
        <dt>Название</dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    <div>
        <form asp-controller="Group" asp-action="DeleteGroup" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Удалить" />
            </div>
        </form>
    </div>
</div>

UniversityMVC/Views/Group/SelectedGroup.cshtml
@model IEnumerable<UniversityMVC.Models.Student>
@{
    ViewData["Title"] = "Home Page";
}

<h3>Список студентов группы @ViewBag.GroupName:</h3>
<table class="table-condensed">
    <tr>
        <td>ID</td>
        <td>Имя</td>
        <td>Фамилия</td>
    </tr>
    @foreach (var student in Model)
    {
        <tr>
            <td>@student.Id</td>
            <td>@student.FirstName</td>
            <td>@student.LastName</td>
            <td><a asp-action="ChangeStudent" asp-controller="Student" asp-route-id="@student.Id">Изменить имя</a></td>
            <td><a asp-action="DeleteStudent" asp-controller="Student" asp-route-id="@student.Id">Удалить</a></td>
        </tr>
    }
</table>